#!/usr/bin/env sh
#
# Script name: prepend
# Description: A bash script for prepending a line text to a file
# Dependencies: coreutils
# GitHub: https://www.github.com/pchstpch/myminiutils
# License: https://www.github.com/pchstpch/LICENSE
# Contributers: Derek Taylor, Muneeb Mennad
#
# Set w/ the flags "-e", "-u", "-o pipefail" cause the script to
# fail if certain things happen, which is a good thing. Otherwise
# we can get hidden bugs that are hard to discover.
set -euo pipefail

# Check if a filename argument is provided
if [ "$#" -ne 1 ]; then
	echo "Usage: prepend <filename>"
	exit
fi

blue="$(tput setaf 4 bold)"
green="$(tput setaf 2 bold)"
reset="$(tput sgr0)"


filename="$1"

# 'read -e' gets user input with readline support
# -p sets the prompt
# -r prevents backslash escapes from being interpreted
echo "Enter text to prepend to file ${blue}$filename${reset}:"
read -e -r -p "${blue}>>>${reset} " input_text

# Prepend the text to the beginning of the file
# Create a temp file, write new text, then original content
temp_file=$(mktemp)

printf "%s\n" "$input_text" > "$temp_file"
cat "$filename" >> "$temp_file"

mv "$temp_file" "$filename"

echo "${green}✓${reset} Text successfully prepended!"
